[package]
name = "todo_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# コマンドライン引数解析
clap = {version = "4.4", features = ["derive"]}
# JSONシリアライズ
serde = {version = "1.0", features = ["derive"]}
# JSONファイルの読み書き
serde_json = "1.0"
